Repository prgrms-be-devcourse/BEDV1_OurHome, pull requests merged in 2021-11, with the labels that each got.

#42 [Market/Voucher] 바우처를 수정할 수 있다
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/controller/VoucherController.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/converter/VoucherConverter.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/FixedVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/PercentVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/Voucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/VoucherDto.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/VoucherType.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/request/RequestVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/DifferentTypeVoucherException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/service/VoucherService.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/controller/VoucherControllerTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/domain/FixedVoucherTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/domain/PercentVoucherTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/service/VoucherServiceTest.java
Labels: 🛒 마켓, 🎨 feat

#53 [Community/User] 유저페이지 조회 기능 구현
  ourhome-community/src/main/java/com/armand/ourhome/community/bookmark/repository/BookmarkRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/like/repository/LikeRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/UserPageResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/service/UserService.java
Labels: 👭 커뮤니티, 🎨 feat

#55 [C/post] 사용자 정보로 게시물 검색 기능 추가
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Content.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Post.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Tag.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/repository/ContentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/repository/PostRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/service/PostService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/entity/ContentTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/entity/PostTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/entity/TagTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/service/PostServiceTest.java
Labels: 👭 커뮤니티, 🎨 feat

#59 [M/voucher-44, 54] 바우처 삭제 및 조회 기능 추가
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/controller/VoucherController.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/VoucherDto.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/VoucherType.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/DifferentTypeVoucherException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/DuplicateVoucherException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/VoucherNotFoundException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/service/VoucherService.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/VoucherIntegrationTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/service/VoucherServiceTest.java
Labels: 🛒 마켓, 🎨 feat

#71 [Community/post] repository 코드 update
  ourhome-community/src/main/java/com/armand/ourhome/community/post/controller/PostController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/ContentDto.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/PostDto.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/mapper/PostMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/repository/ContentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/repository/PostRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/repository/TagRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/service/PostService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/service/PostServiceTest.java
Labels: 👭 커뮤니티, ⚙ chore

#72 [M/order-52] yaml 파일 설정 완료
  ourhome-common/src/main/resources/application-common.yaml
  ourhome-community/src/main/resources/application.yaml
  ourhome-domain/src/main/resources/application-dev.yaml
  ourhome-domain/src/main/resources/application-domain.yaml
  ourhome-domain/src/main/resources/application-local.yaml
  ourhome-domain/src/main/resources/application-prod.yaml
  ourhome-domain/src/main/resources/dev-db.yaml
  ourhome-domain/src/main/resources/prod-db.yaml
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/DeliveryRequest.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/DeliveryResponse.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/OrderItemRequest.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/OrderRequest.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/OrderResponse.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/UserRequest.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/UserResponse.java
  ourhome-market/src/main/resources/application.yaml
  ourhome-market/src/test/java/com/armand/ourhome/market/order/controller/OrderControllerTest.java
Labels: ⚙ chore, ⚡ 공통

#84 [M/order-79] restdocs 추가
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/DeliveryResponse.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/OrderItemRequest.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/OrderRequest.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/OrderResponse.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/mapper/OrderMapper.java
  ourhome-market/src/test/java/com/armand/ourhome/market/order/OrderIntegrationTest.java
Labels: 🛒 마켓, 🔗 test

#81 [C/follow-73] 팔로워/팔로잉 사용자 조회 기능 구현
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/controller/FollowController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/repository/FollowRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/service/FollowService.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/controller/UserController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/FollowPageResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/UserPageResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/service/UserService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/user/controller/UserControllerTest.java
Labels: 👭 커뮤니티, 🎨 feat

#90 [C/comment-29] 댓글 작성 기능 구현
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/controller/CommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/mapper/CreateCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/request/CreateCommentRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/response/CreateCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/entity/Comment.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/exception/PostNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/exception/UserNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/repository/CommentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/service/CommentService.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/util/CommentDateTimeFormatter.java
Labels: 👭 커뮤니티, 🎨 feat

#92 [C/sub comment 66] 답글 작성 기능 구현
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/controller/CommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/request/CreateCommentRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/entity/Comment.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/service/CommentService.java
  ourhome-community/src/main/java/com/armand/ourhome/community/exception/CommentNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/exception/PostNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/exception/UserNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/controller/SubCommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/mapper/CreateSubCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/request/CreateSubCommentRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/response/CreateSubCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/entity/SubComment.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/repository/SubCommentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/service/SubCommentService.java
Labels: 👭 커뮤니티, 🎨 feat

#93 [C/comment-65] 댓글 삭제 기능 구현
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/controller/CommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/entity/Comment.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/service/CommentService.java
Labels: 👭 커뮤니티, 🎨 feat

#96 [C/comment-95] 댓글 삭제 응답 형식 변경
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/controller/CommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/mapper/CreateCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/mapper/RemoveCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/response/RemoveCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/service/CommentService.java
Labels: 👭 커뮤니티, 💥 fix

#97 [C/sub-comment-94] 답글 삭제 기능 구현
  ourhome-community/src/main/java/com/armand/ourhome/community/exception/SubCommentNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/controller/SubCommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/mapper/DestroySubCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/response/DestroySubCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/repository/SubCommentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/service/SubCommentService.java
Labels: 👭 커뮤니티, 🎨 feat

#99 [C/comment-98] 댓글 삭제 방식 변경
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/controller/CommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/mapper/DeleteCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/mapper/RemoveCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/response/DeleteCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/dto/response/RemoveCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/service/CommentService.java
Labels: 👭 커뮤니티, 💥 fix

#101 [C/sub-comment-100] 답글 삭제 응답 변경
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/service/CommentService.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/controller/SubCommentController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/mapper/DeleteSubCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/mapper/DestroySubCommentMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/response/DeleteSubCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/dto/response/DestroySubCommentResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/service/SubCommentService.java
Labels: 👭 커뮤니티, 💥 fix

#105 [C/sub-comment-104] findByComment -> countByComment로 변경
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/service/CommentService.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/repository/SubCommentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/service/SubCommentService.java
Labels: 👭 커뮤니티, 🔧 refactor

#85 [M/item] 리뷰 이미지 업로드, 수정, 삭제 기능 구현
  ourhome-market/src/main/java/com/armand/ourhome/market/item/controller/ItemController.java
  ourhome-market/src/main/java/com/armand/ourhome/market/item/mapper/ItemMapper.java
  ourhome-market/src/main/java/com/armand/ourhome/market/item/service/ItemService.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/controller/ReviewController.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/domain/ReviewImage.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/domain/ReviewImageStatus.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestAddReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestDeleteReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestReviewPages.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestUpdateReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseAddReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseReviewImage.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseUpdateReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/exception/ReviewImageDuplicateException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/exception/ReviewImageNotFoundException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/mapper/ReviewMapper.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/repository/ReviewImageRepository.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/service/ReviewImageService.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/service/ReviewService.java
  ourhome-market/src/test/java/com/armand/ourhome/market/item/controller/ItemControllerTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/item/service/ItemServiceTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/review/controller/ReviewControllerTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/review/repository/ReviewImageRepositoryTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/review/service/ReviewImageServiceTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/review/service/ReviewServiceTest.java
Labels: 🛒 마켓, ⚙ chore, 🎨 feat

#88 [M/wallet-61] 바우처 할당 및 사용 기능 구현
  ourhome-market/src/main/java/com/armand/ourhome/market/order/domain/Order.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/dto/OrderRequest.java
  ourhome-market/src/main/java/com/armand/ourhome/market/order/service/OrderService.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/controller/VoucherController.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/converter/WalletMapper.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/FixedVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/PercentVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/Voucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/Wallet.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/PageResponse.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/WalletDto.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/request/RequestWallet.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/DuplicateWalletException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/WalletNotFoundException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/mapper/VoucherMapper.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/repository/WalletRepository.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/service/VoucherService.java
  ourhome-market/src/test/java/com/armand/ourhome/market/TestHelper.java
  ourhome-market/src/test/java/com/armand/ourhome/market/order/OrderIntegrationTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/order/repository/OrderItemRepositoryTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/order/repository/OrderRepositoryTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/VoucherIntegrationTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/controller/VoucherControllerTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/service/VoucherServiceTest.java
Labels: 🛒 마켓, 🎨 feat

#91 [C/post] 게시물 저장, 상세조회, 삭제, 검색 기능, 게시물 팔로우 여부
  ourhome-community/src/main/java/com/armand/ourhome/community/post/controller/PostController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/controller/common/CriteriaType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/TagDto.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqContent.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqPost.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqTag.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqUserId.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResContent.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResPost.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResReturnId.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResTag.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Content.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Criteria.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/PlaceType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Post.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/ResidentialType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/SquareType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/StyleType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Tag.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/exception/CriteriaNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/exception/PostNotFoundException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/exception/UserNotFountException.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/mapper/PostMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/repository/PostRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/service/PostService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/service/PostServiceTest.java
Labels: 👭 커뮤니티, 🎨 feat

#110 [C/post 89] PageResponse 및 JsonNaming 수정(#89)
  ourhome-community/src/main/java/com/armand/ourhome/community/post/controller/PostController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqContent.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqPost.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqTag.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqUserId.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResContent.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResPost.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResReturnId.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/response/ResTag.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/service/PostService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/service/PostServiceTest.java
Labels: 👭 커뮤니티, ⚡ 공통, 🔧 refactor

#111 [M/Item] JsonNaming 제거, PageResponse 제거
  ourhome-market/src/main/java/com/armand/ourhome/market/item/dto/ItemDto.java
  ourhome-market/src/main/java/com/armand/ourhome/market/item/dto/response/ResponseItem.java
  ourhome-market/src/main/java/com/armand/ourhome/market/item/dto/response/ResponseItemDetail.java
  ourhome-market/src/main/java/com/armand/ourhome/market/item/mapper/ItemMapper.java
  ourhome-market/src/main/java/com/armand/ourhome/market/item/service/ItemService.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/ReviewDto.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestAddReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestDeleteReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestPraiseReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestRemovePraiseReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/request/RequestUpdateReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/PageResponse.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseAddReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseReviewImage.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/dto/response/ResponseUpdateReview.java
  ourhome-market/src/main/java/com/armand/ourhome/market/review/service/ReviewService.java
  ourhome-market/src/test/java/com/armand/ourhome/market/item/controller/ItemControllerTest.java
Labels: 🛒 마켓, ⚙ chore

#115 [C/follow-86] 팔로우 피드 기능 구현
  ourhome-common/src/main/java/com/armand/ourhome/common/api/CursorPageRequest.java
  ourhome-common/src/main/java/com/armand/ourhome/common/api/CursorPageResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/bookmark/repository/BookmarkRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/comment/repository/CommentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/controller/FollowController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/dto/FeedResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/repository/FollowRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/service/FollowService.java
  ourhome-community/src/main/java/com/armand/ourhome/community/like/repository/LikeRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/repository/PostRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/sub_comment/repository/SubCommentRepository.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/controller/UserController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/request/UpdateInfoRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/FollowInfoResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/SignUpResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/Thumbnail.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/UpdateResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/dto/response/UserInfoResponse.java
  ourhome-community/src/main/java/com/armand/ourhome/community/user/service/UserService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/user/controller/UserControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/user/service/UserServiceUnitTest.java
  ourhome-domain/src/main/java/com/armand/ourhome/domain/user/UserRepository.java
Labels: 👭 커뮤니티, 🎨 feat, 🔧 refactor

#117 [M/wallet-108] 피드백 반영
  ourhome-market/src/main/java/com/armand/ourhome/market/OurHomeMarketApplication.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/controller/VoucherController.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/converter/VoucherConverter.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/converter/WalletMapper.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/FixedVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/PercentVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/Voucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/domain/Wallet.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/PageResponse.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/VoucherDto.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/VoucherType.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/WalletDto.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/request/RequestVoucher.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/dto/request/RequestWallet.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/DifferentTypeVoucherException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/DuplicateVoucherException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/DuplicateWalletException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/VoucherNotFoundException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/WalletNotFoundException.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/repository/VoucherRepository.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/repository/WalletRepository.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/service/VoucherService.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/VoucherIntegrationTest.java
  ourhome-market/src/test/java/com/armand/ourhome/market/voucher/service/VoucherServiceTest.java
Labels: 🛒 마켓, 🔧 refactor

#119 [M/wallet-118] 바우처 사용조건(사용 최소금액) 추가
  ourhome-market/src/main/java/com/armand/ourhome/market/order/domain/Order.java
  ourhome-market/src/main/java/com/armand/ourhome/market/voucher/exception/VoucherCannotUseException.java
  ourhome-market/src/test/java/com/armand/ourhome/market/order/OrderIntegrationTest.java
Labels: 🛒 마켓, 🔧 refactor

#116 [C/post 39] 게시물 수정 기능
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqContent.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Content.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/PlaceType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Post.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/ResidentialType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/SquareType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/StyleType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/entity/Tag.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/mapper/PostConverter.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/service/PostService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
Labels: 👭 커뮤니티, 💥 fix

#121 [C/post 83] 팀원분들의 피드백 반영 1차
  ourhome-community/src/main/java/com/armand/ourhome/community/post/controller/PostController.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/controller/common/CriteriaType.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/CreateContentRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/CreatePostRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/CreateTagRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/ReqUserId.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/UpdateContentRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/UpdatePostRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/dto/request/UpdateTagRequest.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/mapper/PostConverter.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/mapper/PostMapper.java
  ourhome-community/src/main/java/com/armand/ourhome/community/post/service/PostService.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/post/service/PostServiceTest.java
Labels: 👭 커뮤니티, 🔧 refactor

#123 [C/Post] 명세서 type을 제시하는 부분에 ',' 추가
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
Labels: 👭 커뮤니티, ⚙ chore

#120 [Common-113] Rest Docs 설정
  .gitignore
  README.md
  ourhome-community/build.gradle
  ourhome-community/src/docs/asciidoc/index.adoc
  ourhome-community/src/main/java/com/armand/ourhome/community/follow/entity/Follow.java
  ourhome-community/src/test/java/com/armand/ourhome/community/Test.java
  ourhome-community/src/test/java/com/armand/ourhome/community/TestHelper.java
  ourhome-community/src/test/java/com/armand/ourhome/community/follow/controller/FollowControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/follow/service/FollowServiceTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/user/controller/UserControllerTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/user/service/UserServiceTest.java
  ourhome-community/src/test/java/com/armand/ourhome/community/user/service/UserServiceUnitTest.java
  ourhome-market/build.gradle
Labels: ⚙ chore, ⚡ 공통

#125 [C/Post-124] user entity detected 에러 해결하기
  ourhome-community/src/test/java/com/armand/ourhome/community/post/controller/PostControllerTest.java
Labels: 👭 커뮤니티, 💥 fix

#127 [C/Post-126] contentTest에서 에러 해결하기
  ourhome-community/src/test/java/com/armand/ourhome/community/post/entity/ContentTest.java
Labels: 👭 커뮤니티, 💥 fix

#128 [Common] build.gradle 수정 (jar 파일 문제)
  ourhome-community/Dockerfile
  ourhome-community/build.gradle
  ourhome-market/build.gradle
Labels: ⚙ chore, 💥 fix, ⚡ 공통
